version: '3.8'
services:

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: django:latest
    tty: true
    working_dir: /usr/src/burulka
    volumes:
      - .:/usr/src/burulka
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./.env
    restart: on-failure
    ports:
      - 5432:5432

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    env_file:
      - ./.env.nginx
    depends_on:
      - django
      - postgres

  myapp:
    image: nginx

volumes:
  postgres_data:
  static_data:
  ssl_data:
