# Generated by Django 4.2.1 on 2024-05-28 11:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('icicle_know', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_url', models.CharField(max_length=128)),
                ('resource_type_id', models.CharField(max_length=128)),
                ('bytes', models.IntegerField()),
                ('description', models.TextField()),
                ('format', models.CharField(max_length=128)),
                ('identifier', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=2)),
                ('publisher', models.CharField(max_length=128)),
                ('relation', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('extent', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_type', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('value_type', models.CharField(max_length=128)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.component')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueAnnotation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotated_value', models.CharField(max_length=128)),
                ('annotation_value', models.CharField(max_length=128)),
                ('value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.value')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stylesheet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.JSONField()),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.component')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root_id', models.CharField(max_length=128)),
                ('header', models.TextField()),
                ('footer', models.TextField()),
                ('stylesheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.stylesheet')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EdgeControlPoint',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('edge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.edge')),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.map')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='edge',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.map'),
        ),
        migrations.AddField(
            model_name='edge',
            name='stylesheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.stylesheet'),
        ),
        migrations.AddField(
            model_name='node',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.component'),
        ),
        migrations.AddField(
            model_name='node',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.map'),
        ),
        migrations.AddField(
            model_name='node',
            name='stylesheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icicle_know.stylesheet'),
        ),
    ]
