# Generated by Django 4.2.1 on 2024-07-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icicle_know', '0003_noderesource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='title',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='title',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='title',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.AddField(
            model_name='component',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concept',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instance',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instance',
            name='item_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='root_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='extent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='format',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='publisher',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='relation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='value',
            name='component_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='value',
            name='value_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='valueannotation',
            name='annotated_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='valueannotation',
            name='annotation_value',
            field=models.CharField(max_length=255),
        ),
    ]
