# Generated by Django 4.2.1 on 2024-09-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icicle_know', '0004_remove_component_title_remove_concept_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbD5C47Fc464AssertedStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('predicate', models.TextField()),
                ('object', models.TextField()),
                ('context', models.TextField()),
                ('termcomb', models.IntegerField()),
            ],
            options={
                'db_table': 'kb_d5c47fc464_asserted_statements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbD5C47Fc464LiteralStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('predicate', models.TextField()),
                ('object', models.TextField(blank=True, null=True)),
                ('context', models.TextField()),
                ('termcomb', models.IntegerField()),
                ('objlanguage', models.CharField(blank=True, max_length=255, null=True)),
                ('objdatatype', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kb_d5c47fc464_literal_statements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbD5C47Fc464NamespaceBinds',
            fields=[
                ('prefix', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('uri', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kb_d5c47fc464_namespace_binds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbD5C47Fc464QuotedStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('predicate', models.TextField()),
                ('object', models.TextField(blank=True, null=True)),
                ('context', models.TextField()),
                ('termcomb', models.IntegerField()),
                ('objlanguage', models.CharField(blank=True, max_length=255, null=True)),
                ('objdatatype', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'kb_d5c47fc464_quoted_statements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KbD5C47Fc464TypeStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.TextField()),
                ('klass', models.TextField()),
                ('context', models.TextField()),
                ('termcomb', models.IntegerField()),
            ],
            options={
                'db_table': 'kb_d5c47fc464_type_statements',
                'managed': False,
            },
        ),
    ]
