from django.urls import path

from icicle_know.api import (
    ConceptListAPI,
    ConceptCreateAPI,
    ConceptViewAPI,
    RelationListAPI,
    RelationCreateAPI,
    RelationViewAPI,
    InstanceListAPI,
    InstanceCreateAPI,
    InstanceViewAPI,
    PropositionListAPI,
    PropositionCreateAPI,
    PropositionViewAPI,
    NodeListAPI,
    NodeCreateAPI,
    NodeViewAPI,
    EdgeListAPI,
    EdgeCreateAPI,
    EdgeViewAPI,
)


urlpatterns = [
    path(
        "concepts/",
        ConceptListAPI.as_view(),
        name="concepts",
    ),
    path(
        "concept/create/",
        ConceptCreateAPI.as_view(),
        name="concept-create",
    ),
    path(
        "concept/<uuid:uuid>/",
        ConceptViewAPI.as_view(),
        name="concept",
    ),
    path(
        "relations/",
        RelationListAPI.as_view(),
        name="relations",
    ),
    path(
        "relation/create/",
        RelationCreateAPI.as_view(),
        name="relation-create",
    ),
    path(
        "relation/<uuid:uuid>/",
        RelationViewAPI.as_view(),
        name="relation",
    ),
    path(
        "instances/",
        InstanceListAPI.as_view(),
        name="instances",
    ),
    path(
        "instance/create/",
        InstanceCreateAPI.as_view(),
        name="instance-create",
    ),
    path(
        "instance/<uuid:uuid>/",
        InstanceViewAPI.as_view(),
        name="instance",
    ),
    path(
        "propositions/",
        PropositionListAPI.as_view(),
        name="propositions",
    ),
    path(
        "proposition/create/",
        PropositionCreateAPI.as_view(),
        name="proposition-create",
    ),
    path(
        "proposition/<uuid:uuid>/",
        PropositionViewAPI.as_view(),
        name="proposition",
    ),
    path(
        "nodes/",
        NodeListAPI.as_view(),
        name="nodes",
    ),
    path(
        "node/create/",
        NodeCreateAPI.as_view(),
        name="node-create",
    ),
    path(
        "node/<uuid:uuid>/",
        NodeViewAPI.as_view(),
        name="node",
    ),
    path(
        "edges/",
        EdgeListAPI.as_view(),
        name="edges",
    ),
    path(
        "edge/create/",
        EdgeCreateAPI.as_view(),
        name="edge-create",
    ),
    path(
        "edge/<uuid:uuid>/",
        EdgeViewAPI.as_view(),
        name="edge",
    ),
]
